version: "3.4"

services:
   # existing DB for Medusa
   # schema: https://github.com/medusajs/medusa/tree/master/packages/medusa/src/models
   medusa-db:
      image: postgres:13
      environment:
        POSTGRES_DB: medusa
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
      restart: always
      volumes:
         - ./database/medusa/existing-schema.pgsql:/docker-entrypoint-initdb.d/1-schema.sql
         - medusa-db-data:/var/lib/postgresql/data/
      networks:
         - medusa-network
      expose:
         - "5432"

   postgrest: # pretend this is the Medusa backend
      image: postgrest/postgrest
      ports:
         - "3000:3000"
      links:
         - medusa-db:medusa-db
      depends_on:
         - medusa-db
      environment:
         PGRST_DB_URI: postgres://test:test@medusa-db:5432/medusa
         PGRST_DB_SCHEMA: api
         PGRST_DB_ANON_ROLE: web_anon
         PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000/"
         # PGRST_JWT_SECRET: '{"kty":"RSA","e":"AQAB","kid":"442d692e-cec3-4917-8164-e97ce25a8e7a","n":"wQ8mDGjqlM03MGKm6Tp9gGFmxcE5Cf4Z6UMa1-i_H-UpilX9PVGLG54TP0NaMMgL4u6wpjI7CPVnowmMO0VvNlZLi9WJBGDj7zY_olMcYwubvb6rWBQ1DDnlnHa4g79_C4CVftUXrAHOhi4TrbjtiSX0f39f6WazfB__L8DtwDc2g5lCLazgXZl2oXn4PV1TmxsV9bKI391T_EbQpE2G-M9nM8mqH5Qj1F2GK5xX2S-_8zY11de2mekqRLfGzU3advbIJrj1ZiCWPC7WKI4MTEpcrki9m929ZbHRoKvDv2BQrq1DM3Ryj6YLgETtwxqmdTgyOOHG_8qmK0Nc9zDmLQ"}'
         # PGRST_ROLE_CLAIM_KEY: '.resource_access.frontend.roles[0]'
      networks:
         - medusa-network

networks:
   main-network:  # reachable from outside
      driver: bridge
   medusa-network:   # not reachable from outside
      driver: bridge

volumes:
   keycloak-db-data:
   medusa-db-data:
